# Generated by Django 2.2.12 on 2021-01-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='files')),
                ('student', models.ManyToManyField(related_name='student_file', to='classroom.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_file', to='classroom.Teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='submitfile',
            name='submitted_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_for_file', to='classroom.ClassFile'),
        ),
        migrations.RenameModel(
            old_name='SubmitAssignment',
            new_name='SubmitFile',
        ),
        migrations.DeleteModel(
            name='ClassAssignment',
        ),
    ]
